/**
 * Mock Data for AI Interview Automation Demo
 *
 * PRODUCTION vs DEMO MAPPING:
 * ---------------------------
 * In production:
 * - Events would stream from Vapi webhooks in real-time
 * - The transcript would be generated by Vapi's speech-to-text
 * - The evaluation would be performed by an LLM (Claude/GPT) analyzing the transcript
 * - Slack notification would be sent via Slack API
 *
 * In this demo:
 * - All data is pre-defined
 * - Events are fired sequentially with artificial delays
 * - This simulates the feel of a real pipeline without external dependencies
 */

import {
  PipelineEvent,
  CandidateReport,
  PipelineEventType,
  VersionInfo,
  SystemVersion,
  InterviewHistoryEntry,
  AuditLogEntry,
  SystemMetrics,
} from './types';

// Helper to generate unique IDs
const generateId = (): string => Math.random().toString(36).substring(2, 9);

// =============================================================================
// VERSION-SPECIFIC EVENT TEMPLATES
// =============================================================================

type EventTemplate = {
  type: PipelineEventType;
  name: string;
  description: string;
  delayMs: number;
};

// MVP Events - Basic flow without persistence or error handling
const MVP_EVENT_TEMPLATES: EventTemplate[] = [
  {
    type: 'call_started',
    name: 'Call Started',
    description: 'Voice agent connected with candidate Sarah Chen',
    delayMs: 500,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q1)',
    description: 'Agent: "Tell me about your experience with distributed systems"',
    delayMs: 1500,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q1)',
    description: 'Candidate responded (47 seconds, transcribed)',
    delayMs: 2000,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q2)',
    description: 'Agent: "Describe a challenging technical problem you solved"',
    delayMs: 1200,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q2)',
    description: 'Candidate responded (62 seconds, transcribed)',
    delayMs: 2200,
  },
  {
    type: 'call_ended',
    name: 'Call Ended',
    description: 'Interview completed. Duration: 5 minutes',
    delayMs: 800,
  },
  {
    type: 'evaluation_done',
    name: 'Evaluation Complete',
    description: 'Basic AI analysis finished',
    delayMs: 2500,
  },
  {
    type: 'slack_sent',
    name: 'Slack Notification',
    description: 'Team notified in Slack',
    delayMs: 600,
  },
];

// 2-Month Events - Production flow with persistence and monitoring
const TWO_MONTH_EVENT_TEMPLATES: EventTemplate[] = [
  {
    type: 'call_started',
    name: 'Call Started',
    description: 'Voice agent connected with candidate Sarah Chen • Session ID: vapi_8x7k2m',
    delayMs: 500,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q1)',
    description: 'Agent: "Tell me about your experience with distributed systems"',
    delayMs: 1200,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q1)',
    description: 'Transcribed: 312 words • Confidence: 94% • Stored to DB',
    delayMs: 1800,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q2)',
    description: 'Agent: "Describe a challenging technical problem you solved"',
    delayMs: 1000,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q2)',
    description: 'Transcribed: 428 words • Confidence: 97% • Stored to DB',
    delayMs: 2000,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q3)',
    description: 'Agent: "Why are you interested in this role?"',
    delayMs: 1000,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q3)',
    description: 'Transcribed: 241 words • Confidence: 92% • Stored to DB',
    delayMs: 1500,
  },
  {
    type: 'call_ended',
    name: 'Call Ended',
    description: 'Interview completed • Duration: 8:24 • Recording saved',
    delayMs: 800,
  },
  {
    type: 'transcript_ready',
    name: 'Transcript Ready',
    description: 'Full transcript: 981 words • Quality Score: 94% • Persisted',
    delayMs: 1200,
  },
  {
    type: 'evaluation_done',
    name: 'Evaluation Complete',
    description: 'AI analysis done • Model: Claude 3.5 • Rubric v2.3 applied',
    delayMs: 2000,
  },
  {
    type: 'slack_sent',
    name: 'Slack Notification',
    description: 'Team notified in #recruiting-pipeline • Delivery confirmed',
    delayMs: 500,
  },
];

// 4-Month Events - Enterprise flow with compliance and audit trails
const FOUR_MONTH_EVENT_TEMPLATES: EventTemplate[] = [
  {
    type: 'call_started',
    name: 'Call Started',
    description: 'Voice agent connected • Session: vapi_8x7k2m • Consent recorded',
    delayMs: 500,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q1)',
    description: 'Technical Q1 from approved rubric v2.3 • Bias-checked',
    delayMs: 1000,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q1)',
    description: '312 words • 94% confidence • Encrypted • Audit logged',
    delayMs: 1500,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q2)',
    description: 'Problem-solving Q2 • Adaptive follow-up enabled',
    delayMs: 800,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q2)',
    description: '428 words • 97% confidence • PII redacted • Audit logged',
    delayMs: 1800,
  },
  {
    type: 'question_asked',
    name: 'Question Asked (Q3)',
    description: 'Motivation Q3 • Culture-fit weighted per rubric',
    delayMs: 800,
  },
  {
    type: 'answer_received',
    name: 'Answer Received (Q3)',
    description: '241 words • 92% confidence • Sentiment analyzed',
    delayMs: 1200,
  },
  {
    type: 'question_asked',
    name: 'Follow-up Question',
    description: 'AI-generated follow-up based on Q2 response analysis',
    delayMs: 1000,
  },
  {
    type: 'answer_received',
    name: 'Follow-up Answer',
    description: '186 words • Depth score: 8.2/10 • Cross-validated',
    delayMs: 1500,
  },
  {
    type: 'call_ended',
    name: 'Call Ended',
    description: 'Duration: 11:42 • Recording encrypted (AES-256) • GDPR compliant',
    delayMs: 600,
  },
  {
    type: 'transcript_ready',
    name: 'Transcript Ready',
    description: '1,167 words • Quality: 95% • Version-controlled • Searchable',
    delayMs: 1000,
  },
  {
    type: 'evaluation_done',
    name: 'Multi-Model Evaluation',
    description: 'Claude + GPT-4 consensus • Calibrated against 847 past interviews',
    delayMs: 2500,
  },
  {
    type: 'slack_sent',
    name: 'Multi-Channel Notification',
    description: 'Slack + Email + ATS update • All confirmations received',
    delayMs: 400,
  },
];

// Map versions to their templates
const VERSION_EVENT_TEMPLATES: Record<SystemVersion, EventTemplate[]> = {
  mvp: MVP_EVENT_TEMPLATES,
  '2-month': TWO_MONTH_EVENT_TEMPLATES,
  '4-month': FOUR_MONTH_EVENT_TEMPLATES,
};

/**
 * Generates mock pipeline events for a specific version
 * In production, these would come from Vapi webhooks and internal event handlers
 */
export function generateMockEvents(version: SystemVersion = 'mvp'): PipelineEvent[] {
  const templates = VERSION_EVENT_TEMPLATES[version];
  return templates.map((template, index) => ({
    id: generateId(),
    timestamp: new Date(Date.now() + index * 1000),
    type: template.type,
    name: template.name,
    description: template.description,
    status: 'pending' as const,
  }));
}

/**
 * Returns the delay (in ms) for each event
 * Used by the demo runner to simulate real-time pipeline execution
 */
export function getEventDelays(version: SystemVersion = 'mvp'): number[] {
  return VERSION_EVENT_TEMPLATES[version].map((t) => t.delayMs);
}

/**
 * Version-specific candidate evaluation reports
 * Each version shows different levels of analysis depth
 */

// MVP Report - Basic evaluation, simple scores
const MVP_CANDIDATE_REPORT: CandidateReport = {
  candidate_name: 'Sarah Chen',
  position: 'Senior Backend Engineer',
  interview_date: '2024-01-15',
  duration_minutes: 5,
  scores: {
    communication: 8,
    experience: 8,
    motivation: 7,
    problem_solving: 7,
    culture_fit: 7,
  },
  summary: [
    '5+ years of experience with distributed systems',
    'Strong technical communication skills',
    'Interest in the role and company',
  ],
  strengths: [
    'Kubernetes experience',
    'Problem-solving mindset',
  ],
  risks: [
    'Limited Go experience',
    'Salary expectations unclear',
  ],
  recommendation: 'Hire',
  confidence: 72,
};

// 2-Month Report - Production evaluation with confidence scores and more detail
const TWO_MONTH_CANDIDATE_REPORT: CandidateReport = {
  candidate_name: 'Sarah Chen',
  position: 'Senior Backend Engineer',
  interview_date: '2024-01-15',
  duration_minutes: 8,
  scores: {
    communication: 8,
    experience: 9,
    motivation: 7,
    problem_solving: 8,
    culture_fit: 8,
  },
  summary: [
    '5+ years of experience with distributed systems at scale',
    'Led migration of monolith to microservices at previous company',
    'Strong technical communication, explains complex concepts clearly',
    'Expressed genuine interest in the company mission and team culture',
    'Mentioned preference for async work, which aligns with team practices',
  ],
  strengths: [
    'Deep expertise in Kubernetes and container orchestration',
    'Experience mentoring junior engineers',
    'Proactive problem-solver with ownership mindset',
    'Track record of delivering under ambiguity',
  ],
  risks: [
    'Limited experience with our specific tech stack (Go)',
    'May need ramp-up time on domain-specific knowledge',
    'Salary expectations at top of approved band',
  ],
  recommendation: 'Hire',
  confidence: 85,
};

// 4-Month Report - Enterprise evaluation with calibration and multi-model consensus
const FOUR_MONTH_CANDIDATE_REPORT: CandidateReport = {
  candidate_name: 'Sarah Chen',
  position: 'Senior Backend Engineer',
  interview_date: '2024-01-15',
  duration_minutes: 12,
  scores: {
    communication: 9,
    experience: 9,
    motivation: 8,
    problem_solving: 9,
    culture_fit: 8,
  },
  summary: [
    '5+ years distributed systems experience at high-scale companies (Stripe, Datadog)',
    'Led successful monolith→microservices migration, reducing deploy time by 70%',
    'Exceptional communication: ranked in top 15% of all candidates interviewed',
    'Alignment score with team values: 87% (calibrated against 847 past hires)',
    'Follow-up responses showed strong depth of understanding (8.2/10)',
    'Sentiment analysis: High enthusiasm, genuine interest indicators',
  ],
  strengths: [
    'Top-tier Kubernetes expertise (ranked in 95th percentile of candidates)',
    'Proven mentorship track record: grew 3 junior engineers to senior level',
    'Ownership mindset validated by specific examples with measurable outcomes',
    'Communication clarity score: 9.1/10 (cross-validated by Claude + GPT-4)',
  ],
  risks: [
    'Go experience: Limited, but strong transfer skills from Rust (similar paradigms)',
    'Domain ramp-up: Est. 4-6 weeks based on similar candidate trajectories',
    'Compensation: At band ceiling, but justified by experience level',
  ],
  recommendation: 'Strong Hire',
  confidence: 94,
};

// Map versions to their reports
export const VERSION_CANDIDATE_REPORTS: Record<SystemVersion, CandidateReport> = {
  mvp: MVP_CANDIDATE_REPORT,
  '2-month': TWO_MONTH_CANDIDATE_REPORT,
  '4-month': FOUR_MONTH_CANDIDATE_REPORT,
};

// Keep backward compatibility
export const MOCK_CANDIDATE_REPORT = TWO_MONTH_CANDIDATE_REPORT;

/**
 * Icon mapping for event types
 * Used by the UI to show appropriate icons for each event
 */
export const EVENT_ICONS: Record<PipelineEventType, string> = {
  call_started: '📞',
  question_asked: '❓',
  answer_received: '💬',
  call_ended: '📴',
  transcript_ready: '📝',
  evaluation_done: '🎯',
  slack_sent: '📨',
};

/**
 * Color mapping for event types
 * Used by the UI for visual differentiation
 */
export const EVENT_COLORS: Record<PipelineEventType, string> = {
  call_started: 'bg-green-500',
  question_asked: 'bg-blue-500',
  answer_received: 'bg-purple-500',
  call_ended: 'bg-orange-500',
  transcript_ready: 'bg-yellow-500',
  evaluation_done: 'bg-pink-500',
  slack_sent: 'bg-indigo-500',
};

// =============================================================================
// SYSTEM MATURITY DATA
// =============================================================================

/**
 * Version definitions
 * Each version answers a different question about system readiness
 */
export const VERSION_INFO: Record<SystemVersion, VersionInfo> = {
  mvp: {
    id: 'mvp',
    label: 'MVP',
    tagline: 'Does it work?',
    description: 'Proof of concept demonstrating the core interview automation flow',
  },
  '2-month': {
    id: '2-month',
    label: '2-Month',
    tagline: 'Can we rely on it?',
    description: 'Production-ready with persistence, stability, and operational monitoring',
  },
  '4-month': {
    id: '4-month',
    label: '4-Month',
    tagline: 'Can we trust it at scale?',
    description: 'Enterprise-ready with governance, compliance, and scale operations',
  },
};

/**
 * MVP Limitations
 * Explicitly lists what the MVP does NOT handle
 * In production: these would be addressed progressively
 */
export const MVP_LIMITATIONS = [
  {
    id: 'no-persistence',
    title: 'No Persistence',
    description: 'Data exists only in memory during the session',
    icon: '💾',
  },
  {
    id: 'no-retries',
    title: 'No Failure Handling',
    description: 'Failed steps are not retried or recovered',
    icon: '🔄',
  },
  {
    id: 'no-roles',
    title: 'No User Roles',
    description: 'No authentication or authorization layer',
    icon: '👤',
  },
  {
    id: 'no-compliance',
    title: 'No Compliance Logic',
    description: 'No data retention, GDPR, or audit trails',
    icon: '📋',
  },
  {
    id: 'no-history',
    title: 'No Historical Comparison',
    description: 'Cannot compare candidates or track patterns',
    icon: '📊',
  },
];

/**
 * Mock interview history (2-month version)
 * In production: would come from database queries
 * Note: Using static dates to avoid SSR hydration mismatches
 */
export const MOCK_INTERVIEW_HISTORY: InterviewHistoryEntry[] = [
  {
    id: 'int-001',
    candidateName: 'Sarah Chen',
    position: 'Senior Backend Engineer',
    date: '2024-01-15',
    status: 'completed',
    recommendation: 'Hire',
  },
  {
    id: 'int-002',
    candidateName: 'Marcus Johnson',
    position: 'Frontend Developer',
    date: '2024-01-14',
    status: 'completed',
    recommendation: 'Maybe',
  },
  {
    id: 'int-003',
    candidateName: 'Emily Rodriguez',
    position: 'DevOps Engineer',
    date: '2024-01-13',
    status: 'failed',
  },
  {
    id: 'int-004',
    candidateName: 'David Kim',
    position: 'Senior Backend Engineer',
    date: '2024-01-12',
    status: 'completed',
    recommendation: 'No Hire',
  },
];

/**
 * Mock audit log entries (4-month version)
 * In production: would be immutable entries in a secure audit database
 * Note: Using static timestamps to avoid SSR hydration mismatches
 */
export const MOCK_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'audit-001',
    timestamp: new Date('2024-01-15T14:32:00'),
    actor: 'system@interview-ai.com',
    action: 'EVALUATION_GENERATED',
    resource: 'candidate/sarah-chen',
    details: 'Using evaluation logic v2.3',
  },
  {
    id: 'audit-002',
    timestamp: new Date('2024-01-15T14:31:00'),
    actor: 'hiring-manager@company.com',
    action: 'REPORT_VIEWED',
    resource: 'candidate/sarah-chen',
  },
  {
    id: 'audit-003',
    timestamp: new Date('2024-01-15T14:30:00'),
    actor: 'system@interview-ai.com',
    action: 'TRANSCRIPT_STORED',
    resource: 'interview/int-001',
    details: 'Encrypted at rest (AES-256)',
  },
  {
    id: 'audit-004',
    timestamp: new Date('2024-01-15T14:29:00'),
    actor: 'recruiter@company.com',
    action: 'INTERVIEW_INITIATED',
    resource: 'candidate/sarah-chen',
  },
];

/**
 * Mock system metrics (4-month version)
 * In production: would come from Prometheus/Datadog/etc.
 */
export const MOCK_SYSTEM_METRICS: SystemMetrics = {
  avgLatencyMs: 234,
  completionRate: 94.2,
  interviewsToday: 47,
  queueDepth: 3,
};

/**
 * Evaluation rubric versions (4-month version)
 * In production: versioned evaluation prompts stored in database
 */
export const EVALUATION_VERSIONS = [
  { version: 'v2.3', date: '2024-01-15', status: 'active', changes: 'Added culture fit weighting' },
  { version: 'v2.2', date: '2024-01-02', status: 'archived', changes: 'Improved technical scoring' },
  { version: 'v2.1', date: '2023-12-18', status: 'archived', changes: 'Initial production rubric' },
];

// =============================================================================
// EVENT EXPLANATIONS FOR CLICKABLE STEPS
// =============================================================================

/**
 * Detailed explanations for each pipeline event
 * These explain how each step would work in a real production system
 */
export interface EventExplanation {
  eventType: PipelineEventType;
  title: string;
  summary: string;
  inProduction: {
    trigger: string;
    dataFlow: string[];
    technologies: string[];
    errorHandling: string;
  };
}

export const EVENT_EXPLANATIONS: Record<PipelineEventType, EventExplanation> = {
  call_started: {
    eventType: 'call_started',
    title: 'Call Started - Verbindungsaufbau',
    summary: 'Der Voice Agent (Vapi) initiiert einen Telefonanruf mit dem Kandidaten. Sobald die Verbindung steht, wird ein Webhook an unseren Server gesendet.',
    inProduction: {
      trigger: 'Vapi Webhook: POST /api/webhooks/vapi mit event_type: "call.started"',
      dataFlow: [
        'Vapi ruft die Telefonnummer des Kandidaten an',
        'Kandidat nimmt ab → Vapi sendet "call.started" Webhook',
        'n8n empfängt den Webhook und erstellt einen Interview-Record',
        'Interview-Status wird auf "in_progress" gesetzt',
        'Dashboard wird via Webhook/WebSocket aktualisiert',
      ],
      technologies: ['Vapi API', 'n8n Workflow', 'Airtable/Notion', 'Webhook'],
      errorHandling: 'Bei Verbindungsfehler: 3 Retry-Versuche mit exponential backoff. Bei dauerhaftem Fehler: Kandidat wird per Email benachrichtigt.',
    },
  },

  question_asked: {
    eventType: 'question_asked',
    title: 'Question Asked - Frage gestellt',
    summary: 'Der Voice Agent stellt dem Kandidaten eine vordefinierte Interview-Frage. Die Fragen werden aus einem konfigurierbaren Fragenkatalog geladen.',
    inProduction: {
      trigger: 'Vapi Webhook: "assistant.speech.started" kombiniert mit Prompt-Tracking',
      dataFlow: [
        'Vapi Voice Agent spricht die nächste Frage aus dem Prompt',
        'Webhook "speech.started" wird an n8n gesendet',
        'n8n matched die gesprochenen Worte mit dem Fragenkatalog',
        'Frage-Event wird mit Zeitstempel protokolliert',
        'Frontend zeigt die aktuelle Frage an',
      ],
      technologies: ['Vapi Prompt System', 'n8n Workflow', 'Airtable Question Bank'],
      errorHandling: 'Falls Vapi die Frage nicht korrekt vorliest: Fallback auf Text-to-Speech Retry. Frage wird als "potentially_unclear" markiert.',
    },
  },

  answer_received: {
    eventType: 'answer_received',
    title: 'Answer Received - Antwort erhalten',
    summary: 'Die Antwort des Kandidaten wird in Echtzeit transkribiert und gespeichert. Vapi nutzt Whisper für Speech-to-Text mit hoher Genauigkeit.',
    inProduction: {
      trigger: 'Vapi Webhook: "speech.transcript.final" nach Sprechpause des Kandidaten',
      dataFlow: [
        'Kandidat spricht seine Antwort',
        'Vapi streamt Audio zu Whisper für Echtzeit-Transkription',
        'Nach erkannter Sprechpause wird finales Transkript gesendet',
        'n8n speichert Transkript mit Zeitstempeln in Airtable/Notion',
        'Antwort wird der entsprechenden Frage zugeordnet',
      ],
      technologies: ['OpenAI Whisper', 'Vapi Streaming', 'n8n', 'Airtable/Notion'],
      errorHandling: 'Bei schlechter Audioqualität: Confidence Score wird gespeichert. Unter 70% Confidence: Antwort wird für manuelle Review markiert.',
    },
  },

  call_ended: {
    eventType: 'call_ended',
    title: 'Call Ended - Anruf beendet',
    summary: 'Das Interview ist abgeschlossen. Der Voice Agent verabschiedet sich und die Verbindung wird getrennt. Alle Daten werden für die Auswertung vorbereitet.',
    inProduction: {
      trigger: 'Vapi Webhook: "call.ended" mit Grund (completed, error, timeout)',
      dataFlow: [
        'Voice Agent spricht Verabschiedung',
        'Verbindung wird beendet → Webhook wird gesendet',
        'n8n aktualisiert Interview-Status auf "completed"',
        'Audio-Recording URL wird gespeichert',
        'n8n triggert Transkript-Aggregation Workflow',
      ],
      technologies: ['Vapi Call Recording', 'n8n Workflow', 'Airtable/Notion'],
      errorHandling: 'Bei unerwartetem Abbruch: Interview wird als "incomplete" markiert. Kandidat erhält Option für neuen Termin.',
    },
  },

  transcript_ready: {
    eventType: 'transcript_ready',
    title: 'Transcript Ready - Transkript fertig',
    summary: 'Alle Einzelantworten werden zu einem vollständigen Interview-Transkript zusammengeführt. Das Transkript wird strukturiert und für die AI-Analyse vorbereitet.',
    inProduction: {
      trigger: 'n8n Workflow: Nach Call-Ende automatisch getriggert',
      dataFlow: [
        'n8n sammelt alle Antwort-Transkripte aus Airtable/Notion',
        'Transkripte werden chronologisch sortiert',
        'Vollständiges Dokument wird erstellt (Frage + Antwort Paare)',
        'Transkript wird gespeichert',
        'Nächster Workflow-Schritt wird getriggert: AI Evaluation',
      ],
      technologies: ['n8n Workflow', 'Airtable/Notion', 'HTTP Request Node'],
      errorHandling: 'Bei fehlenden Antworten: Transkript wird mit Lücken-Markierung erstellt. Quality Score wird berechnet.',
    },
  },

  evaluation_done: {
    eventType: 'evaluation_done',
    title: 'Evaluation Complete - Bewertung abgeschlossen',
    summary: 'Eine AI (Claude/GPT) analysiert das vollständige Transkript und erstellt eine strukturierte Bewertung mit Scores, Stärken, Risiken und einer Empfehlung.',
    inProduction: {
      trigger: 'n8n Workflow: Nach Transkript-Aggregation',
      dataFlow: [
        'n8n lädt das vollständige Transkript',
        'Transkript wird via OpenAI/Anthropic Node an AI gesendet',
        'AI analysiert Antworten nach vordefinierten Kriterien',
        'Strukturierte JSON-Antwort wird geparst',
        'Candidate Report wird in Airtable/Notion gespeichert',
      ],
      technologies: ['n8n OpenAI Node', 'Claude/GPT API', 'Airtable/Notion'],
      errorHandling: 'Bei AI-Fehler: Retry mit exponential backoff (max 3x). Bei persistentem Fehler: Fallback auf manuelle Review.',
    },
  },

  slack_sent: {
    eventType: 'slack_sent',
    title: 'Slack Notification - Team benachrichtigt',
    summary: 'Das Hiring-Team wird automatisch über Slack informiert. Die Nachricht enthält eine Zusammenfassung und einen Link zum vollständigen Report.',
    inProduction: {
      trigger: 'n8n Workflow: Nach erfolgreicher Evaluation',
      dataFlow: [
        'n8n Evaluation-Workflow löst Slack-Node aus',
        'Message wird mit Report-Summary formatiert',
        'Slack API wird via n8n Slack Node aufgerufen',
        'Message enthält Kandidaten-Info, Scores und Link',
        'Delivery Status wird geloggt',
      ],
      technologies: ['n8n Slack Node', 'Slack API', 'Webhook'],
      errorHandling: 'Bei Slack API Fehler: n8n Retry. Alternative Kanäle (Email) als Fallback.',
    },
  },
};
