/**
 * TypeScript types for the AI Interview Automation Demo
 *
 * PRODUCTION vs DEMO MAPPING:
 * ---------------------------
 * In a real Vapi-based system:
 * - PipelineEvent would come from Vapi webhooks (call.started, speech.transcript, etc.)
 * - CandidateReport would be generated by an LLM analyzing the transcript
 * - Events would flow through a real event bus (Redis, Kafka, etc.)
 *
 * In this demo:
 * - All events are mocked and fired on timers
 * - The candidate report is static mock data
 */

// Represents a single event in the interview pipeline
export interface PipelineEvent {
  id: string;
  timestamp: Date;
  type: PipelineEventType;
  name: string;
  description: string;
  metadata?: Record<string, unknown>;
  status: 'pending' | 'active' | 'completed';
}

// All possible event types in the pipeline
export type PipelineEventType =
  | 'call_started'
  | 'question_asked'
  | 'answer_received'
  | 'call_ended'
  | 'transcript_ready'
  | 'evaluation_done'
  | 'slack_sent';

// Scoring categories for candidate evaluation
export interface CandidateScores {
  communication: number;      // 1-10 scale
  experience: number;         // 1-10 scale
  motivation: number;         // 1-10 scale
  problem_solving: number;    // 1-10 scale
  culture_fit: number;        // 1-10 scale
}

// The final evaluation report for a candidate
export interface CandidateReport {
  candidate_name: string;
  position: string;
  interview_date: string;
  duration_minutes: number;
  scores: CandidateScores;
  summary: string[];
  strengths: string[];
  risks: string[];
  recommendation: 'Strong Hire' | 'Hire' | 'Maybe' | 'No Hire';
  confidence: number;         // 0-100%
}

// Demo state management
export interface DemoState {
  isRunning: boolean;
  currentEventIndex: number;
  events: PipelineEvent[];
  report: CandidateReport | null;
  phase: 'idle' | 'running' | 'completed';
}

// =============================================================================
// SYSTEM MATURITY LEVELS
// =============================================================================
// The system evolves through three maturity stages, each answering a different question:
// - MVP: "Does it work?" (proof of concept)
// - 2-Month: "Can we rely on it?" (operational stability)
// - 4-Month: "Can we trust it at scale?" (enterprise governance)

export type SystemVersion = 'mvp' | '2-month' | '4-month';

export interface VersionInfo {
  id: SystemVersion;
  label: string;
  tagline: string;
  description: string;
}

// Extended event with stability tracking (2-month+)
export interface ExtendedPipelineEvent extends PipelineEvent {
  executionStatus?: 'pending' | 'running' | 'completed' | 'failed';
  retryCount?: number;
  persistedAt?: Date;
}

// Interview history entry (2-month+)
export interface InterviewHistoryEntry {
  id: string;
  candidateName: string;
  position: string;
  date: string;
  status: 'completed' | 'failed' | 'in_progress';
  recommendation?: 'Strong Hire' | 'Hire' | 'Maybe' | 'No Hire';
}

// Audit log entry (4-month)
export interface AuditLogEntry {
  id: string;
  timestamp: Date;
  actor: string;
  action: string;
  resource: string;
  details?: string;
}

// System metrics (4-month)
export interface SystemMetrics {
  avgLatencyMs: number;
  completionRate: number;
  interviewsToday: number;
  queueDepth: number;
}
